title: Kim's SoD Guides
description: Raid guides for WoW Season of Discovery.
theme: just-the-docs

url: https://yttrium-tyclief.github.io/sod-guides/
color_scheme: dark

plugins:
  - jekyll_bootstrap5_tabs

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  blacktrial:
    title: Black Trial Changes
    color: purple
    opacity: 0.6
  tip:
    title: Tip
    color: blue
  example:
    title: Example
    color: green
  heat1:
    title: Heat Level 1
    color: blue
  heat2:
    title: Heat Level 2
    color: yellow
  heat3:
    title: Heat Level 3
    color: red
  druid:
    title: Druid
    color: druid
  hunter:
    title: Hunter
    color: hunter
  mage:
    title: Mage
    color: mage
  paladin:
    title: Paladin
    color: paladin
  priest:
    title: Priest
    color: priest
  rogue:
    title: Rogue
    color: rogue
  shaman:
    title: Shaman
    color: shaman
  warlock:
    title: Warlock
    color: warlock
  warrior:
    title: Warrior
    color: warrior